spring:
  datasource:
    url: jdbc:mysql://yamanote.proxy.rlwy.net:40609/railway
    username: root
    password: LofWYUWXAKncyfmRllDPPWcswLStwsyi
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      minimum-idle: 2
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

server:
  port: 8080